# Generated by Django 3.1.4 on 2021-05-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('team1', models.CharField(default='', max_length=100)),
                ('team2', models.CharField(default='', max_length=100)),
                ('toss_winner', models.CharField(default='', max_length=100)),
                ('toss_decision', models.CharField(default='', max_length=100)),
                ('result', models.CharField(default='', max_length=100)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(default='', max_length=100)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(default='', max_length=100)),
                ('venue', models.CharField(default='', max_length=100)),
                ('umpire1', models.CharField(default='', max_length=100)),
                ('umpire2', models.CharField(default='', max_length=100)),
                ('umpire3', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(default='', max_length=100)),
                ('bowling_team', models.CharField(default='', max_length=100)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(default='', max_length=100)),
                ('non_striker', models.CharField(default='', max_length=100)),
                ('bowler', models.CharField(default='', max_length=100)),
                ('is_super_over', models.IntegerField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(default='', max_length=100)),
                ('dismissal_kind', models.CharField(default='', max_length=100)),
                ('fielder', models.CharField(default='', max_length=100)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matches')),
            ],
        ),
    ]
